@php
    $payload = $request->lgu_dromic_payload ?? [];
    $row = fn ($label, $value) => '<tr><th>'.$label.'</th><td>'.e(filled($value) ? $value : '-').'</td></tr>';
@endphp
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $request->reference_number }}</title>
    <style>
        @page { margin: 32px 38px; }
        body { font-family: DejaVu Sans, sans-serif; color: #0f172a; font-size: 11px; line-height: 1.45; }
        h1, h2, h3, p { margin: 0; }
        .header { text-align: center; border-bottom: 2px solid #0f766e; padding-bottom: 10px; margin-bottom: 16px; }
        .agency { font-size: 10px; text-transform: uppercase; letter-spacing: .06em; color: #115e59; font-weight: 700; }
        h1 { font-size: 18px; margin-top: 4px; }
        .ref { margin-top: 6px; font-weight: 700; color: #334155; }
        .section { margin-top: 14px; }
        .section h2 { font-size: 12px; text-transform: uppercase; letter-spacing: .05em; color: #0f766e; border-bottom: 1px solid #cbd5e1; padding-bottom: 4px; margin-bottom: 6px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #cbd5e1; padding: 6px 7px; vertical-align: top; }
        th { width: 32%; text-align: left; background: #f1f5f9; color: #475569; text-transform: uppercase; font-size: 9px; letter-spacing: .04em; }
        .narrative { white-space: pre-line; text-align: justify; border: 1px solid #cbd5e1; padding: 10px; min-height: 120px; }
        .routing { background: #f8fafc; }
        .footer { margin-top: 26px; font-size: 9px; color: #64748b; border-top: 1px solid #cbd5e1; padding-top: 8px; }
    </style>
</head>
<body>
    <div class="header">
        <p class="agency">DSWD Field Office Caraga · Disaster Response Operations Management Integrated System (DROMIS)</p>
        <h1>LGU DROMIC Report and Request for Relief Augmentation</h1>
        <p class="ref">{{ $request->reference_number }} · Submitted {{ optional($request->submitted_at)->format('d M Y, h:i A') }}</p>
    </div>

    <div class="section">
        <h2>Requesting LGU</h2>
        <table>
            {!! $row('LGU / Agency', $request->requesting_agency) !!}
            {!! $row('Requester', $request->requester) !!}
            {!! $row('Requester Position', $request->requester_position) !!}
            {!! $row('Contact Number', $request->contact_number) !!}
            {!! $row('Address', $request->requester_address) !!}
        </table>
    </div>

    <div class="section">
        <h2>Incident and Affected Population</h2>
        <table>
            {!! $row('Incident', $request->incident?->name ?? data_get($payload, 'incident_name')) !!}
            {!! $row('Incident Date', optional($request->incident?->incident_date)->format('d M Y') ?: data_get($payload, 'incident_date')) !!}
            {!! $row('Province', $request->province) !!}
            {!! $row('City / Municipality', $request->municipality) !!}
            {!! $row('Barangay/s', $request->barangay) !!}
            {!! $row('Affected Families', data_get($payload, 'affected_families')) !!}
            {!! $row('Affected Persons', data_get($payload, 'affected_persons')) !!}
            {!! $row('Displaced Families', data_get($payload, 'displaced_families')) !!}
            {!! $row('Damaged Houses', data_get($payload, 'damaged_houses')) !!}
            {!! $row('Casualties / Other Details', data_get($payload, 'casualties')) !!}
        </table>
    </div>

    <div class="section">
        <h2>Situation Narrative</h2>
        <div class="narrative">{{ $request->lgu_dromic_narrative ?: $request->assessment_summary }}</div>
    </div>

    <div class="section">
        <h2>Relief Augmentation Request</h2>
        <table>
            {!! $row('Identified Needs / Gaps', data_get($payload, 'needs')) !!}
            {!! $row('Requested Relief Augmentation', data_get($payload, 'relief_requested')) !!}
            {!! $row('Recommendations', $request->recommendations) !!}
            {!! $row('LGU Remarks', $request->remarks) !!}
        </table>
    </div>

    <div class="section routing">
        <h2>DRMD Routing Record</h2>
        <table>
            {!! $row('Current Routing Status', str($request->lgu_routing_status ?: $request->status)->replace('_', ' ')->title()) !!}
            {!! $row('DRMD AA Remarks', $request->drmd_aa_remarks) !!}
            {!! $row('DRMD Chief Directive', $request->drmd_chief_remarks) !!}
            {!! $row('Assigned Section / Program', $request->drmd_assigned_section) !!}
            {!! $row('Assigned Employee', $request->drmdAssignedUser?->name) !!}
        </table>
    </div>

    <p class="footer">Generated by DROMIS. This PDF is based on the LGU encoded DROMIC/SitRep-style data and the recorded DRMD routing actions.</p>
</body>
</html>
