@php
    $items = $transaction['items'] ?? [];
    $rows = array_merge($items, array_fill(0, max(0, 11 - count($items)), null));
    $itemRowHeight = count($rows) > 11 ? max(9, 154 / count($rows)) : 14;
    $tracking = $transaction['tracking'] ?? [];
    $from = $transaction['warehouse'] ?? '';
    $to = $transaction['delivery_site'] ?: $transaction['recipient'];
    $requested = $signatories['requested_by'] ?? ['name' => $transaction['encoded_by'] ?? '', 'designation' => ''];
    $approved = $signatories['approved_by'] ?? ['name' => '', 'designation' => ''];
    $issued = $signatories['issued_by'] ?? ['name' => $tracking['release_witnessed_by'] ?? '', 'designation' => ''];
    $received = ['name' => $tracking['received_by'] ?? '', 'designation' => $tracking['receiver_position'] ?? ''];
@endphp
<!doctype html><html><head><meta charset="utf-8"><style>
@page{margin:16pt 20pt}*{box-sizing:border-box}body{margin:0;color:#080808;font-family:DejaVu Sans,sans-serif;font-size:7.3pt}table{width:100%;border-collapse:collapse;table-layout:fixed}td,th{border:.7pt solid #111;padding:2.5pt 3pt;vertical-align:middle;line-height:1.08}.no-border,.no-border td{border:0}.center{text-align:center}.right{text-align:right}.top{vertical-align:top}.label{font-weight:800}.tiny{font-size:6.2pt}.logo{width:74pt;max-height:25pt}.bp{width:22pt;max-height:25pt;margin-left:3pt}.title{font-size:16pt;font-weight:900;text-align:center;letter-spacing:.2pt;white-space:nowrap}.code{text-align:right;font-size:5.2pt;font-weight:700;white-space:nowrap}.ref{background:#fff200;font-size:9pt;font-weight:900;text-align:center;padding:4pt 1pt;border:.7pt solid #111;white-space:nowrap}.meta td{font-size:7.5pt}.section-rule td,.section-rule th{border-top:2pt solid #111}.items th{font-size:7.4pt;font-weight:900;text-align:center}.items .head th{height:24pt}.nothing{text-align:center;font-weight:800;letter-spacing:.3pt;white-space:nowrap}.purpose-label{text-align:right;font-size:7.5pt;font-weight:900}.purpose-kind{text-align:center;font-weight:800}.purpose-text{height:18pt;font-size:7.3pt}.yellow{background:#fff200}.sig th{font-size:7pt;white-space:nowrap}.sig .space td{height:20pt}.sig .name td{text-align:center;font-size:5.9pt;font-weight:900;text-transform:uppercase;white-space:nowrap;padding-left:1pt;padding-right:1pt}.sig .designation td{text-align:center;font-size:5.8pt;font-style:italic;white-space:nowrap;padding-left:1pt;padding-right:1pt}.note{text-align:center;font-size:6pt;font-style:italic;margin:1pt 0}.lower-grid>tbody>tr>td{border:0;padding:0;vertical-align:top}.lower-left{width:52%;padding-right:4pt!important}.lower-right{width:48%;padding-left:4pt!important}.inspection th{height:18pt;text-align:left;font-size:6.2pt}.inspection td{font-size:6.2pt}.inspection .space td{height:21pt}.logistics th{background:#d9d9d9;text-align:center;font-size:7.2pt;padding:2.5pt}.logistics td{padding:2pt;font-size:6.3pt}.logistics .key{text-align:right;width:48%;white-space:nowrap}.logistics .value{height:11pt}.footer{position:fixed;bottom:-10pt;left:0;right:0;text-align:center;font-family:DejaVu Serif,serif;font-size:5pt;color:#444}
</style></head><body>
<table class="no-border"><tr><td style="width:20%"><img class="logo" src="{{ public_path('images/dswd_logo_3.png') }}"><img class="logo bp" src="{{ public_path('images/Bagong_PilipinasTransparent.png') }}"></td><td class="title">SUPPLY TRANSFER FORM</td><td style="width:25%"><div class="code">NRLMB-GQF-0013<br>REV 2/20 JUL 2020</div><div class="ref">{{ $transaction['stf_reference'] }}</div></td></tr></table>
<table class="meta section-rule"><colgroup><col style="width:24%"><col style="width:29%"><col style="width:20%"><col style="width:27%"></colgroup><tr><td class="label">REQUESTING DIVISION:</td><td>DRMD</td><td class="label">DATE:</td><td>{{ filled($transaction['transaction_date'] ?? null) ? \Carbon\Carbon::parse($transaction['transaction_date'])->format('F j, Y') : '' }}</td></tr><tr><td class="label">FROM WAREHOUSE:</td><td>{{ $from }}</td><td class="label">TO WAREHOUSE:</td><td>{{ $to }}</td></tr></table>
<table class="items section-rule"><colgroup><col style="width:8%"><col style="width:7%"><col style="width:29%"><col style="width:12%"><col style="width:15%"><col style="width:29%"></colgroup><tr class="head"><th>QTY</th><th>UNIT</th><th>ITEM</th><th>BATCH NO.</th><th>PO NO.</th><th>REMARKS<br><span class="tiny">(EXPIRATION DATE, CONDITION, ETC.)</span></th></tr>@foreach($rows as $index=>$item)<tr class="line"><td class="center">{{ $item ? number_format((float)($item['quantity'] ?? 0), ((float)($item['quantity'] ?? 0)==(int)($item['quantity'] ?? 0)?0:2)) : '' }}</td><td class="center">{{ $item['unit'] ?? '' }}</td><td class="{{ $index===count($items) && $item===null ? 'nothing' : 'center' }}">{{ $index===count($items) && $item===null && count($items)>0 ? '***** nothing follows *****' : ($item['item'] ?? '') }}</td><td class="center">{{ $item['batch_number'] ?? '' }}</td><td></td><td class="right tiny">@if($item){{ filled($item['brand'] ?? null)?'Brand: '.$item['brand'].'. ':'' }}{{ filled($item['expiry'] ?? null)?'Expiry: '.\Carbon\Carbon::parse($item['expiry'])->format('M Y').'. ':'' }}{{ $item['remarks'] ?? '' }}@endif</td></tr>@endforeach</table>
<table class="section-rule"><colgroup><col style="width:14%"><col style="width:19%"><col style="width:19%"><col style="width:48%"></colgroup><tr><td class="purpose-label">PURPOSE:</td><td class="purpose-kind">Prepositioning</td><td class="purpose-kind yellow">{{ str_contains(strtolower($transaction['purpose'] ?? ''),'replenish')?'Replenishment':'' }}</td><td></td></tr><tr><td></td><td class="purpose-text" colspan="3">{{ $transaction['purpose'] ?? '' }}</td></tr></table>
<table class="sig section-rule"><colgroup><col style="width:14%"><col style="width:21.5%"><col style="width:21.5%"><col style="width:21.5%"><col style="width:21.5%"></colgroup><tr><th></th><th>REQUESTED BY:</th><th>APPROVED BY:</th><th>ISSUED BY:</th><th>RECEIVED BY:</th></tr><tr class="space"><td class="right label">SIGNATURE:</td><td></td><td></td><td></td><td></td></tr><tr class="name"><td class="right label">NAME:</td><td>{{ $requested['name'] }}</td><td>{{ $approved['name'] }}</td><td>{{ $issued['name'] }}</td><td>{{ $received['name'] }}</td></tr><tr class="designation"><td class="right label">DESIGNATION:</td><td>{{ $requested['designation'] }}</td><td>{{ $approved['designation'] }}</td><td>{{ $issued['designation'] }}</td><td>{{ $received['designation'] }}</td></tr><tr><td class="right label">DATE:</td><td></td><td></td><td></td><td class="center">{{ $tracking['received_date'] ?? '' }}</td></tr></table>
<p class="note">Note: Fill up the details below only if applicable.</p>
<table class="lower-grid"><tr><td class="lower-left"><table class="inspection"><colgroup><col style="width:26%"><col style="width:37%"><col style="width:37%"></colgroup><tr><th></th><th>VISUAL INSPECTION<br>CONDUCTED BY:</th><th>ENCODED TO DATABASE:</th></tr><tr class="space"><td class="right label">SIGNATURE:</td><td></td><td></td></tr><tr><td class="right label">NAME:</td><td></td><td></td></tr><tr><td class="right label">DESIGNATION:</td><td></td><td></td></tr><tr><td class="right label">DATE:</td><td></td><td></td></tr><tr><th colspan="3">INSPECTOR REMARKS:</th></tr><tr><td colspan="3" style="height:34pt"></td></tr></table></td><td class="lower-right"><table class="logistics"><tr><th colspan="2">TRANSPORTER</th></tr><tr><td class="key">Driver's Name:</td><td class="value">{{ $tracking['driver_name'] ?? '' }}</td></tr><tr><td class="key">Vehicle Plate Number:</td><td>{{ $tracking['vehicle_plate_number'] ?? '' }}</td></tr><tr><td class="key">Driver's License Number:</td><td>{{ $tracking['driver_license_number'] ?? '' }}</td></tr><tr><td class="key">Signature:</td><td></td></tr><tr><td class="key">Contact Number:</td><td>{{ $tracking['driver_contact'] ?? '' }}</td></tr><tr><th colspan="2">RECEIVER</th></tr><tr><td class="key">Contact Number:</td><td>{{ $tracking['receiver_contact'] ?? '' }}</td></tr><tr><td class="key">Position:</td><td>{{ $tracking['receiver_position'] ?? '' }}</td></tr><tr><td class="key">Arrival Date:</td><td>{{ $tracking['received_date'] ?? '' }}</td></tr><tr><td class="key">Arrival Time:</td><td>{{ $tracking['received_time'] ?? '' }}</td></tr><tr><th colspan="2">ESCORT</th></tr><tr><td class="key">Signature:</td><td></td></tr><tr><td class="key">Name of Escort:</td><td>{{ $tracking['escort_name'] ?? '' }}</td></tr><tr><td class="key">Contact Number:</td><td>{{ $tracking['escort_contact'] ?? '' }}</td></tr></table></td></tr></table>
<div class="footer">DSWD Field Office Caraga · Regional Resource Operations Section</div>
</body></html>
